### ISSUE TITLE
Base site on a modern layout

### ISSUE THREAD

**Issue by MattTheTekie** [RPCSX/rpcsx-site#3]
I'm willing to redo the site in the Nintendo 3DS guide layout. Would a PR be accepted?
https://github.com/hacks-guide/Guide_3DS

**Comment by OCDkirby** [comment]
Feel free to make changes as long as you stay within the vue.js ecosystem (and preferably within naive-ui and the theme ecosystem I have set up in `App.vue`). 

The only things I wouldn't touch are the code-behind the dark mode button (it breaks easily) and the content of the wiki menu in the top bar (it's web scraping). 

If you're looking to create more informational pages, consider whether the changes would be better off in [the project wiki](https://github.com/RPCSX/wiki).

**Comment by MattTheTekie** [comment]
> 

I'll get on it within the week. Thank you.

**Comment by MattTheTekie** [comment]
> 

Ah it's Jekyll and not Vue.js based. I'm willing to do the PR but it's at you're command. I've been busy and have some free time today.

**Comment by OCDkirby** [comment]
The homepage is Vue, the wiki for informational content is Jekyll. And yeah, go ahead!

**Comment by MattTheTekie** [comment]
> The homepage is Vue, the wiki for informational content is Jekyll. And yeah, go ahead!

Il go do it! I was referring to the repo I linked, but I appreciate the help. I will start doing it now. Thank you!

**Comment by MattTheTekie** [comment]
I streamed part 1 at my Odysee page if you would like to check it out. Here's the link. https://odysee.com/@mattdoestech726:5/Designing-the-RPCSX-site:7

- Matt.

**Comment by MattTheTekie** [comment]
I can't finish it up today because of some family issues I can't talk about. My life is on pause, and I will be back tomorrow to do the job.

- Matt.

**Comment by MattTheTekie** [comment]
I got the wiki out. Il push that in a PR rn. Il do the site sometime around.
